server: 
  port: 7042
spring:
  redis:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes: 10.10.170.154:7012,10.10.170.154:7001,10.10.170.154:7003
    timeout: 1000 #连接超时（毫秒）
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
